### ISSUE TITLE
ObjectStorage tests fail occasionally on slow GitHub actions

### ISSUE THREAD

**Issue by lzpap** [iotaledger/hive.go#154]
## Bug description

`ObjectStorage` tests fail with 10 min timeout sometimes on CI.
One example is: https://github.com/iotaledger/hive.go/runs/922612527?check_suite_focus=true

The log says that two goroutines are waiting to acquire `objectStorage.cacheMutex` lock. Somewhere in the code the lock is not released or is still in use.
```
2020-07-29T09:18:23.0737955Z ?   	github.com/iotaledger/hive.go/objectstorage	[no test files]
2020-07-29T09:28:17.2860513Z panic: test timed out after 10m0s
2020-07-29T09:28:17.2860851Z 
2020-07-29T09:28:17.2861026Z goroutine 204031 [running]:
2020-07-29T09:28:17.2861157Z testing.(*M).startAlarm.func1()
2020-07-29T09:28:17.2861361Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/testing/testing.go:1377 +0xdf
2020-07-29T09:28:17.2861589Z created by time.goFunc
2020-07-29T09:28:17.2861776Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/time/sleep.go:168 +0x44
2020-07-29T09:28:17.2861930Z 
2020-07-29T09:28:17.2862069Z goroutine 1 [chan receive, 9 minutes]:
2020-07-29T09:28:17.2862314Z testing.(*T).Run(0xc0000acb00, 0xa46595, 0x1d, 0xa5ccb8, 0x48e301)
2020-07-29T09:28:17.2862509Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/testing/testing.go:961 +0x377
2020-07-29T09:28:17.2862749Z testing.runTests.func1(0xc0000ac300)
2020-07-29T09:28:17.2862941Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/testing/testing.go:1202 +0x78
2020-07-29T09:28:17.2863164Z testing.tRunner(0xc0000ac300, 0xc0000bbdc0)
2020-07-29T09:28:17.2863353Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/testing/testing.go:909 +0xc9
2020-07-29T09:28:17.2863599Z testing.runTests(0xc00000f480, 0x1032460, 0xd, 0xd, 0x0)
2020-07-29T09:28:17.2863979Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/testing/testing.go:1200 +0x2a7
2020-07-29T09:28:17.2864950Z testing.(*M).Run(0xc000116180, 0x0)
2020-07-29T09:28:17.2865146Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/testing/testing.go:1117 +0x176
2020-07-29T09:28:17.2865360Z main.main()
2020-07-29T09:28:17.2865471Z 	_testmain.go:74 +0x135
2020-07-29T09:28:17.2865545Z 
2020-07-29T09:28:17.2865688Z goroutine 6 [chan receive, 9 minutes]:
2020-07-29T09:28:17.2865860Z github.com/iotaledger/hive.go/objectstorage.init.0.func1()
2020-07-29T09:28:17.2866307Z 	/home/runner/work/hive.go/hive.go/objectstorage/leak_detection.go:146 +0x43
2020-07-29T09:28:17.2866567Z created by github.com/iotaledger/hive.go/objectstorage.init.0
2020-07-29T09:28:17.2866846Z 	/home/runner/work/hive.go/hive.go/objectstorage/leak_detection.go:144 +0x35
2020-07-29T09:28:17.2867018Z 

this one is waiting on the cacheMutex:
2020-07-29T09:28:17.2867187Z goroutine 16 [semacquire, 9 minutes]: 
2020-07-29T09:28:17.2867654Z sync.runtime_SemacquireMutex(0xc0009ee92c, 0x7f0408309800, 0x0)
2020-07-29T09:28:17.2868367Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/runtime/sema.go:71 +0x47
2020-07-29T09:28:17.2868601Z sync.(*RWMutex).RLock(...)
2020-07-29T09:28:17.2868786Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/sync/rwmutex.go:50
2020-07-29T09:28:17.2869137Z github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).deepIterateThroughCachedElements(0xc0009ee900, 0xc00028ed50, 0xc000058e20, 0xc000109800)
2020-07-29T09:28:17.2869426Z 	/home/runner/work/hive.go/hive.go/objectstorage/object_storage.go:916 +0x495
2020-07-29T09:28:17.2869718Z github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).flush(0xc0009ee900)
2020-07-29T09:28:17.2869987Z 	/home/runner/work/hive.go/hive.go/objectstorage/object_storage.go:889 +0xf2
2020-07-29T09:28:17.2870265Z github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).Shutdown(0xc0009ee900)
2020-07-29T09:28:17.2870533Z 	/home/runner/work/hive.go/hive.go/objectstorage/object_storage.go:473 +0x33
2020-07-29T09:28:17.2870803Z github.com/iotaledger/hive.go/objectstorage/test.TestStoreIfAbsentTriggersOnce(0xc0000acb00)
2020-07-29T09:28:17.2871095Z 	/home/runner/work/hive.go/hive.go/objectstorage/test/objectstorage_test.go:364 +0x2a9
2020-07-29T09:28:17.2871330Z testing.tRunner(0xc0000acb00, 0xa5ccb8)
2020-07-29T09:28:17.2871522Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/testing/testing.go:909 +0xc9
2020-07-29T09:28:17.2871730Z created by testing.(*T).Run
2020-07-29T09:28:17.2871920Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/testing/testing.go:960 +0x350
2020-07-29T09:28:17.2872071Z 
2020-07-29T09:28:17.2872218Z goroutine 10 [select]:
2020-07-29T09:28:17.2872422Z github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc00006d1c0)
2020-07-29T09:28:17.2872692Z 	/home/runner/work/hive.go/hive.go/objectstorage/batch_writer.go:144 +0x13c
2020-07-29T09:28:17.2872881Z created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
2020-07-29T09:28:17.2873147Z 	/home/runner/work/hive.go/hive.go/objectstorage/batch_writer.go:44 +0x93
2020-07-29T09:28:17.2873330Z 
2020-07-29T09:28:17.2873465Z goroutine 21 [select]:
2020-07-29T09:28:17.2873740Z github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc000180240)
2020-07-29T09:28:17.2874009Z 	/home/runner/work/hive.go/hive.go/objectstorage/batch_writer.go:144 +0x13c
2020-07-29T09:28:17.2874295Z created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
2020-07-29T09:28:17.2874562Z 	/home/runner/work/hive.go/hive.go/objectstorage/batch_writer.go:44 +0x93
2020-07-29T09:28:17.2874709Z 

this one is waiting on the cacheMutex:
2020-07-29T09:28:17.2874865Z goroutine 142572 [semacquire, 9 minutes]:
2020-07-29T09:28:17.2875096Z sync.runtime_SemacquireMutex(0xc0009ee928, 0x0, 0x0)
2020-07-29T09:28:17.2875283Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/runtime/sema.go:71 +0x47
2020-07-29T09:28:17.2875423Z sync.(*RWMutex).Lock(0xc0009ee920)
2020-07-29T09:28:17.2875672Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/sync/rwmutex.go:103 +0x88
2020-07-29T09:28:17.2875973Z github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).releaseObject(0xc001582400, 0xc0012b8f00)
2020-07-29T09:28:17.2876356Z 	/home/runner/work/hive.go/hive.go/objectstorage/batch_writer.go:124 +0x43
2020-07-29T09:28:17.2876643Z github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).runBatchWriter(0xc001582400)
2020-07-29T09:28:17.2876912Z 	/home/runner/work/hive.go/hive.go/objectstorage/batch_writer.go:170 +0x251
2020-07-29T09:28:17.2877195Z created by github.com/iotaledger/hive.go/objectstorage.(*BatchedWriter).StartBatchWriter
2020-07-29T09:28:17.2877548Z 	/home/runner/work/hive.go/hive.go/objectstorage/batch_writer.go:44 +0x93
2020-07-29T09:28:17.2877787Z FAIL	github.com/iotaledger/hive.go/objectstorage/test	600.013s
```

It must be a write lock that holds it because one of them that is trying to acquire it is a read lock.
One suspicious part of the code where it could not have been release is this method: https://github.com/iotaledger/hive.go/blob/6d42d7d03fe306680fa29c70d22142db85f96570/objectstorage/object_storage.go#L534-L649

## Steps To reproduce the bug

1.  Try to run tests on GitHub actions and you will see it most likely.

The issue never happens when running the tests locally on your machine.

Maybe related to #147

**Comment by muXxer** [comment]
There is a deadlock between the flush method and the batch_writer.
The batch_writer wants to release an object but the flush method wants to deep iterate through all objects.
I have a full goroutine stacktrace of the testcase "TestStoreIfAbsentTriggersOnce" were this deadlock occured.

https://ybin.me/p/d2786f1df3af6e19#Exa3qW7y1vJeGkBIh+z7q6dl4YrcjlhvL2kExQ4g87A=
